// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxizvjbdqmnmmeyvtbbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94aXp2amJkcW1ubW1leXZ0YmJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDkxMDAsImV4cCI6MjA2MTg4NTEwMH0._6qk-dZKvRytLXWUg8iQvLKTGkvTikYKcsbi4tXqPoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);